<?php

namespace Deg540\PHPTestingBoilerplate\Test;

use PHPUnit\Framework\TestCase;
use Deg540\PHPTestingBoilerplate\Ohce;

class OhceKataTest extends TestCase
{
    private Ohce $ohce;

    /**
     * @setup
     */
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->ohce = new Ohce(); //Asi lo declaramos fuera de los test para no declarar lo mismo en cada test
    }

    /**
     * @test
     */
    public function when_String_given_return_reverted_String()
    {
        $returnedValue = $this->ohce->revert("hola");
        $this->assertEquals("aloh", $returnedValue);
    }

    /**
     * @test
     */
    public function when_palindrome_given_return_i_like_it()
    {
        $returnedValue = $this->ohce->revert("oto");
        $this->assertEquals("¡Bonita Palabra!", $returnedValue);
    }

    /**
     * @test
     */
    public function when_name_given_return_it_with_hello()
    {
        $returnedValue = $this->ohce->revert("ohce Ainhoa");
        $this->assertStringContainsString("Ainhoa", $returnedValue);
    }

    /**
     * @test
     */
    public function when_Stop_given_return_goodbye_and_name()
    {
        $returnedValue = $this->ohce->revert("Stop!");
        $this->assertStringContainsString("Adiós", $returnedValue);
    }

}